# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres

    container_name: "e4-pg"
    tty: true # Enables debugging capabilities when attached to this container.
    environment:
      - POSTGRES_PASSWORD=psql
    stdin_open: true

    volumes:
      - ../.data/pg:/var/lib/postgresql/data
  web:
    image: docker.io/bitnami/node:18
    container_name: "e4-http"
    tty: true # Enables debugging capabilities when attached to this container.
    links:
      - db
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../:/app
