# NOTE version is important for mem_limit, no swarm
version: "2.4"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres

    container_name: "e4-pg"
    env_file: ./.env
    tty: true # Enables debugging capabilities when attached to this container.
    # stdin_open: true
    volumes:
      - ../.data/pg:/var/lib/postgresql/data
  meili:
    image: getmeili/meilisearch:v1.4.2
    container_name: "e4-meili"
    env_file: ./.env

    #for direct debug
    ports:
      - 7700:7700
    volumes:
      - ../.data/meili:/meili_data
  web:
    mem_limit: 1G
    build:
      context: .
      dockerfile: ./Dockerfile.nodejs
    container_name: "e4-http"
    tty: true # Enables debugging capabilities when attached to this container.
    depends_on:
      - meili
      - db
    links:
      - meili
      - db
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../:/app
